#!/bin/bash
app=coquelicot

# Retrieve arguments
domain=$1
path=$2
admin=$3
is_public=$4

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install dependencies and Coquelicot Debian packages
sudo apt-get -y -qq install rubygems libxml2-dev libxslt-dev coquelicot
#sudo gem install bundler
#bundle install --deployment
#bundle exec coquelicot start

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
 #  unprotected_uris allows SSO credentials to be passed anyway.
  sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
