#!/bin/bash
app=coquelicot

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app admin)
is_public=$(sudo yunohost app setting $app is_public)

# Remove Debian packages
bundle exec coquelicot stop
sudo apt-get -y -qq remove rubygems libxml2-dev libxslt-dev coquelicot

# Remove configuration files
#sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
